### ISSUE TITLE
No model image

### ISSUE THREAD

**Issue by mtehonica** [t0nyz0/BambuBoard#4]
I'm only getting the "Loading..." rather than the model image. How can I troubleshoot that? Everything else appears to be working fine, except filament weight.

**Comment by t0nyz0** [comment]
This is almost always because of the username/password being incorrect. My username is my email, sometimes I've seen people put in their 'username' instead of the email.  This could be because I named the setting 'username' ha. But I think thats what Bambu calls it in the API. 

```
BambuBoard_bambuUsername
BambuBoard_bambuPassword
```

Here is a test harness that isolates the code that gets the API info into a script:
[bambuCheck.txt](https://github.com/user-attachments/files/16602158/bambuCheck.txt)

1. Change this to MJS extension. (Should be 'bambuCheck.mjs')
2. Run the following:
```
npm install node-fetch
```

Then run the script to test:

```
node bambuCheck.mjs username-email password
```


Correct login info (Success):
![image](https://github.com/user-attachments/assets/f72320a0-1c0c-4f78-a98a-2a8089345324)


Fail:
![image](https://github.com/user-attachments/assets/b2454cd6-1715-43f4-a66f-90bb913b0a15)

**Comment by mtehonica** [comment]
Had a feeling that was related to an authentication issue but just didn't know how to troubleshoot it.

Looks like that is confirmed using your test code.

```
root@a2ebba118d36:/app# node bambuCheck.mjs username-email password
Authentication failed with status: 400
Error: Error: Authentication failed
    at file:///app/bambuCheck.mjs:28:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I hardcoded my username/password into bambuCheck.mjs and it appears to authenticate correctly. My guess is it's a special character escape issue.

```
body: JSON.stringify({ account: "<REDACTED>", password: "<REDACTED>", apiError: '' })
```

```
Response: {
  imageUrl: 'https://bbl-prod-us-model.s3.dualstack.us-west-1.amazonaws.com/<REDACTED>',
  modelTitle: 'ttyt3dClearRainbow.stl',
  modelWeight: 17.27,
  modelCostTime: 2420,
  totalPrints: 105,
  deviceName: 'Alpha',
  deviceModel: 'X1 Carbon',
  bedType: 'textured_plate'
}
```

**Comment by t0nyz0** [comment]
Ahh I see, that is interesting.

**Comment by mtehonica** [comment]
I don't think I was clear in my response :)

I still can't get this to work using the config file. I could only get it to work when I hardcoded my Bambu credentials into the bambuCheck.mjs. I also changed my password so it no longer had a "!" in it and still not working.

**Comment by t0nyz0** [comment]
> I don't think I was clear in my response :)
> 
> I still can't get this to work using the config file. I could only get it to work when I hardcoded my Bambu credentials into the bambuCheck.mjs. I also changed my password so it no longer had a "!" in it and still not working.

Got it, that makes sense. I went back and tested on my isolated test machine and I'm getting the same issue. Give me a bit I'll figure it out.

**Comment by t0nyz0** [comment]
Ok I have noticed that special characters cause some issues. I'll see if I can fix that. Just out of curiosity, any other special characters in your username or password that might be suspect?
